# Application Configuration

# MongoDB Configuration
mongo {
  uri = "mongodb://localhost:27017"
  database = "FacilityDB"
}

# Play Framework Configuration
play {
  modules.enabled += "main.DayWiseTasks.CaseStudies.CaseStudy1.modules.Module"
  server {
    http {
      address = "0.0.0.0"
      port = 9000
    }
  }
  filters {
    enabled += "play.filters.cors.CORSFilter"
    cors {
      pathPrefixes = ["/"]  # Only enable CORS for paths starting with /api
      allowedOrigins = ["*"]   # Allow all origins
      allowedHttpMethods = ["GET", "POST", "PUT", "DELETE"]
      allowedHttpHeaders = ["Accept", "Origin", "Content-Type", "X-Auth-Token", "Authorization"]
    }
    hosts {
      allowed = ["."]
    }
  }
  http.filters = "security.Filters"
}

# Kafka Configuration
kafka {
  bootstrap.servers = "localhost:9092"
  topics {
    RoomServiceNotifications = "RoomServiceNotifications"
    WifiServiceNotifications = "WifiServiceNotifications"
    RestaurantServiceNotifications = "RestaurantServiceNotifications"
  }
}

# Logging Configuration
logger {
  application = DEBUG
}
